version: "3.8"

services:
  db-mysql:
    stdin_open: true
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=testdb
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - ./project-mysql-data:/var/lib/mysq
    tty: true
